{
    parserClass="com.chaottic.toyle.parser.ToyleParser"
    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
    psiClassPrefix="Toyle"
    psiImplClassSuffix="Impl"
    psiPackage="com.chaottic.toyle.parser"
    elementTypeHolderClass="com.chaottic.toyle.parser.ToyleTypes"
    elementTypeClass="com.chaottic.toyle.parser.ToyleElementType"
    tokenTypeClass="com.chaottic.toyle.parser.ToyleTokenType"
    psiImplUtilClass="com.chaottic.toyle.ToylePsiUtil"
}

file ::= PACKAGE IDENTIFIER (IMPORT IDENTIFIER)* class* (CONST|VAR GLOBAL_NAME)* LINE_COMMENT*

NUMBER
STRING_LITERAL

class ::= IDENTIFIER (INHERIT IDENTIFIER)? (OPEN_SCOPE (OVERRIDE)* CLOSE_SCOPE)?

property ::= LINE_COMMENT*